---
#apiVersion: batch/v1  # use this once on on k8s 1.21
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cfle
  namespace: cfle-prod
  labels:
    app: cfle
spec:
  schedule: "30 16 * * *"  # Everyday at 4:30 PM
  jobTemplate:
    metadata:
      namespace: cfle-prod
      labels:
        app: cfle
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 180
      template:
        metadata:
          namespace: cfle-prod
          labels:
            app: cfle
        spec:
          serviceAccountName: cfle-sa
          imagePullSecrets:
            - name: <image-pull-secret>
          containers:
          - name: cfle
            image: docker.io/freedomben/cfle:20211004184552
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: cfle-config
              - secretRef:
                  name: cfle-secrets
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfle-config
  namespace: cfle-prod
  labels:
    app: cfle
data:
  TEST_CERT: 'yes' # will use let's encrypt sandbox for test cert. Change or remove for real cert (subject to rate limiting)
  FORCE_RENEWAL: 'no' # Will renew even if not needed
  CLOUDFLARE_EMAIL: 'ben@example.com'
  DOMAINS: 'example.com,*.example.com'
  TLS_CERT_SECRET_NAME: '<secret-name-full-chain>'
  K8S_NAMESPACE: ''  # Namespace in which to put the secret.  Defaults to current namespace
  SLACK_CHANNEL_DEBUG: '#infra-debug'
  SLACK_CHANNEL_INFO: '#infra-info'
  SLACK_CHANNEL_WARNING: '#infra-warn'
  SLACK_CHANNEL_ERROR: '#infra-error'
  SLACK_CHANNEL_SUCCESS: '#infra-error'
  SLACK_USERNAME: "CFLE - Lets Encrypt Certificate Renewer - Prod"
  SLACK_ICON_EMOJI: ':lock:'
  DIE_DELAY_SECS: '28800' # Wait 8 hours before exiting after failure (for debugging)

