---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tls-cert-renewal-sa
  namespace: tls-cert-renewal-ns
automountServiceAccountToken: true
secrets:
imagePullSecrets:
  - name: <image-pull-secret>

    #---
    #apiVersion: rbac.authorization.k8s.io/v1
    #kind: ClusterRole
    #metadata:
    #  name: tls-cert-renewal-role
    #rules:
    #- apiGroups:
    #  - ""
    #  resources:
    #  - secrets
    #  - namespaces
    #  verbs:
    #  - get
    #  - list
    #  - create
    #  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tls-cert-renewal-role
  namespace: tls-cert-renewal-ns
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - get
  - list
  - create
  - delete

    #---
    #apiVersion: rbac.authorization.k8s.io/v1
    #kind: ClusterRoleBinding
    #metadata:
    #  name: tls-cert-renewal-rb
    #  namespace: tls-cert-renewal-ns
    #roleRef:
    #  apiGroup: rbac.authorization.k8s.io
    #  kind: ClusterRole
    #  name: tls-cert-renewal-role
    #subjects:
    #- kind: ServiceAccount
    #  name: tls-cert-renewal-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tls-cert-renewal-rb
  namespace: tls-cert-renewal-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tls-cert-renewal-role
subjects:
- kind: ServiceAccount
  name: tls-cert-renewal-sa
  namespace: tls-cert-renewal-ns
