---
#apiVersion: batch/v1  # use this once on on k8s 1.21
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: tls-cert-renewal
  namespace: tls-cert-renewal-ns
  labels:
    app: tls-cert-renewal
spec:
  schedule: "0 0 8 * *"  # Once a month at midnight on the 8th of each month
  jobTemplate:
    metadata:
      namespace: tls-cert-renewal-ns
      labels:
        app: tls-cert-renewal
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 180
      template:
        metadata:
          namespace: tls-cert-renewal-ns
          labels:
            app: tls-cert-renewal
        spec:
          serviceAccountName: tls-cert-renewal-sa
          imagePullSecrets:
            - name: <image-pull-secret>
          containers:
          - name: tls-cert-renewal
            image: docker.io/freedomben/cfle:20210915131847
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: tls-cert-renewal-config
              - secretRef:
                  name: tls-cert-renewal-secrets
          restartPolicy: Never

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tls-cert-renewal-config
  namespace: tls-cert-renewal-ns
  labels:
    app: tls-cert-renewal
data:
  TEST_CERT: 'yes' # will use let's encrypt sandbox for test cert. Change or remove for real cert (subject to rate limiting)
  FORCE_RENEWAL: 'yes' # Will renew even if not needed
  CLOUDFLARE_EMAIL: 'ben@example.com'
  DOMAINS: 'example.com,*.example.com'
  TLS_CERT_SECRET_NAME: '<secret-name-full-chain>'
  K8S_NAMESPACE: ''  # Namespace in which to put the secret.  Defaults to current namespace
  SLACK_INFO_CHANNEL: 'infra-info'
