---
apiVersion: v1
kind: Secret
metadata:
  name: tls-cert-renewal-secrets
  namespace: tls-cert-renewal-ns
  labels:
    app: tls-cert-renewal
type: Opaque
stringData:
  CLOUDFLARE_API_TOKEN: '<cf_token>'

